language: ruby
rvm: 2.4.4
cache: bundler
sudo: false
git:
  # travis uses shallow clones (git clone --depth 50). The default is too small.
  # Increasing the default to enable `git describe`
  depth: 100
env:
  global:
  - TRAVIS=true
  # speed up "gem install nokogiri" by using systems libxml2
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - CRM_TENANT=crmconnector
  - CRM_LOGIN=root
  # CRM_API_KEY:
  - secure: "HFGK2lZQdFlz8AxSoJOKMm5wfraqkN2rOCPicaH9/iczKo92/iPcxA5bgNT8Qu1TFSUN8otETIaTKBZTD9+d97Ikd3E9KmRxrTQ/6dMhwizavooLQaX5uem7/QLhCMld58PruyoxGaPUMqGAtwiZPfk2wyPIV16vo0y3PG/r7sE="
matrix:
  exclude:
    - rvm: 2.4.4
  include:
    - env: "TASK=travis"
      rvm: 2.4.4
      gemfile: gemfiles/rails_4.gemfile
    - env: "TASK=yard"
      rvm: 2.4.4

script: bundle exec rake $TASK
